/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as PreviewImport } from './routes/preview';
import { Route as TestImport } from './routes/test';

// Create/Update Routes

const TestRoute = TestImport.update({
  path: '/test',
  getParentRoute: () => rootRoute,
} as any);

const PreviewRoute = PreviewImport.update({
  path: '/preview',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/preview': {
      id: '/preview';
      path: '/preview';
      fullPath: '/preview';
      preLoaderRoute: typeof PreviewImport;
      parentRoute: typeof rootRoute;
    };
    '/test': {
      id: '/test';
      path: '/test';
      fullPath: '/test';
      preLoaderRoute: typeof TestImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  PreviewRoute,
  TestRoute,
});

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/preview",
        "/test"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/preview": {
      "filePath": "preview.tsx"
    },
    "/test": {
      "filePath": "test.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
