/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root';
import { Route as CartGenerationImport } from './routes/card-generation';
import { Route as IndexImport } from './routes/index';

// Create/Update Routes

const CardGenerationRoute = CartGenerationImport.update({
  path: '/card-generation',
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    '/card-generation': {
      id: '/card-generation';
      path: '/card-generation';
      fullPath: '/card-generation';
      preLoaderRoute: typeof CartGenerationImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({ IndexRoute, CardGenerationRoute });

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/card-generation"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/card-generation": {
      "filePath": "card-generation.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
